version: "2"

services:
  code:
    image: tianon/true
    volumes:
      - ./code:/var/www/
  
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  workspace:
    build: images/workspace
    tty: true
    volumes_from:
      - code
    links:
      - mailhog
      - mysql
      - redis
    user: ${DEFAULT_UID}

  php-fpm:
    build: images/php-fpm
    restart: always
    volumes_from:
      - code
    links:
      - mailhog
      - mysql
      - redis

  web:
    build: images/web
    restart: always
    ports:
      - 80:80
    links:
      - php-fpm
      - mysql
      - redis
      - mailhog
    volumes_from:
      - code
    volumes:
      - ./images/web/conf.d/:/etc/nginx/conf.d/
      - ./images/web/sites-available/:/etc/nginx/sites-available/

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports: 
      - 1025:1025
      - 8025:8025

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

