#!/bin/bash
ERROR=0

YELLOW=$(tput setaf 3)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
NC=$(tput sgr0)
echo

if [ ! -d code ]; then
    printf "$RED%s$NC\n" "code directory not found."
    mkdir code

    if [ $? -eq 0 ]; then
        printf "$GREEN%s$NC\n" "code directory was created. It is like htdocs directory for your environment"
    else
        ERROR=1
    fi
fi

if [ ! -f sites.sh ]; then
    echo "sites.sh not found."
    cp ./examples/sites.sh.example ./sites.sh

    if [ $? -eq 0 ]; then
        printf "sites.sh was created. Map your vhost and document root there\n"
    else
        ERROR=1
    fi
fi

if [ "$ERROR" -ne 1 ]; then
    if [ -f includes/$1 ]; then
        cd includes/ && DEFAULT_UID=$(id -u):$(id -g) ./$1
    else
        printf "Usage:\n  ./lempctl [COMMAND]\n\n"
        printf "Available commands :\n"
        SCRIPTS=includes/*
        for f in $SCRIPTS
        do
            PUBLIC=$(cat $f | grep "\#\# " | cut -c3-100)
            if [ "$PUBLIC" != "" ]; then
                printf "  $YELLOW$(basename $f)$NC\t$PUBLIC\n" | expand -t 35
            fi
        done
    fi
fi
